apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deploy
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: mbrignone/notification_microservice
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: notification-configmap
            - secretRef:
                name: notification-secret
